server:
  port: 8060
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb://workingscorpion.com:50809/ourblogtest
logging:
  level:
    org.springframework.data.mongodb: DEBUG